project_name: gup
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
    - go generate ./...
    - ./scripts/completions.sh
builds:
  - main: .
    ldflags:
      - -s -w -X github.com/nao1215/gup/internal/cmdinfo.Version=v{{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
    - completions/*
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
nfpms:
  - maintainer: 'Naohiro CHIKAMATSU <n.chika156@gmail.com>'
    description: gup - Update binaries installed by 'go install'
    homepage: https://github.com/nao1215/gup
    license: Apache License 2.0
    formats:
      - deb
      - rpm
      - apk
    contents:
      - src: ./completions/gup.bash
        dst: /usr/share/bash-completion/completions/gup
        file_info:
          mode: 0644
      - src: ./completions/gup.fish
        dst: /usr/share/fish/vendor_completions.d/gup.fish
        file_info:
          mode: 0644
      - src: ./completions/gup.zsh
        dst: /usr/share/zsh/vendor-completions/_gup
        file_info:
          mode: 0644
brews:
  - name: gup
    description: gup - Update binaries installed by 'go install'
    license: Apache License 2.0
    repository:
      owner: nao1215
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    # Ref. https://carlosbecker.com/posts/golang-completions-cobra/
    install: |-
      bin.install "gup"
      bash_completion.install "completions/gup.bash" => "gup"
      zsh_completion.install "completions/gup.zsh" => "gup"
      fish_completion.install "completions/gup.fish"    
