name: FreeBSD, OpenBSD, NetBSD Test

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os.host }}
    strategy:
      matrix:
        os:
          - name: freebsd
            architecture: x86-64
            version: "13.2"
            host: macos-12

          - name: openbsd
            architecture: x86-64
            version: "7.3"
            host: macos-12

          - name: netbsd
            architecture: x86-64
            version: "9.3"
            host: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Test on ${{ matrix.os.name }}
        uses: cross-platform-actions/action@v0.15.0
        with:
          operating_system: ${{ matrix.os.name }}
          architecture: ${{ matrix.os.architecture }}
          version: ${{ matrix.os.version }}
          shell: bash
          memory: 5G
          cpu_count: 4
          run: |
            pkg install -y go
            go mod download
            go test -race -v ./...
