name: FreeBSDTest

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-12
    name: A job to run test in FreeBSD
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1"
          check-latest: true
      - name: Test in FreeBSD
        id: test
        uses: vmactions/freebsd-vm@v0
        with:
          run: |
            go mod download
            go test -race -v ./...
